### ISSUE TITLE
Error creating transport: Unsupported transport (PJSIP_EUNSUPTRANSPORT) [status=171060]

### ISSUE THREAD

**Issue by y-luis-rojo** [irontec/bbs#1]
Hi. I am getting the error below when trying to use *bbs*:

```
$ bbs -c examples/simple.yaml -e examples/multiple/environment.yaml -vvv -k -o results.xml
11:40:51.722 os_core_unix.c !pjlib 2.5.5 for POSIX initialized
11:40:51.722 sip_endpoint.c  .Creating endpoint instance...
11:40:51.722          pjlib  .select() I/O Queue created (0xb869d0)
11:40:51.722 sip_endpoint.c  .Module "mod-msg-print" registered
11:40:51.722 sip_transport.  .Transport manager created.
11:40:51.722   pjsua_core.c  .PJSUA state changed: NULL --> CREATED
WARNING: no real random source present!
11:40:51.727   pjsua_core.c  .pjsua version 2.5.5 for Linux-3.10.3.94/x86_64/glibc-2.17 initialized
11:40:51.727   pjsua_core.c  Error creating transport: Unsupported transport (PJSIP_EUNSUPTRANSPORT) [status=171060]
Exception: Object: Lib, operation=create_transport(), error=Unknown error 171060
=============== call from alice to bob (simple.yaml) =======================
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/bbs/session.py", line 97, in run
    Lib.instance().thread_register(("thread_%d" % self.thread.ident))
AttributeError: 'NoneType' object has no attribute 'thread_register'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/bbs/session.py", line 97, in run
    Lib.instance().thread_register(("thread_%d" % self.thread.ident))
AttributeError: 'NoneType' object has no attribute 'thread_register'

Scenario has failed [20 timeout reached]
Scenario has failed
```

Can you help me find out why?

**Comment by Kaian** [comment]
Fixed in #2
