### ISSUE TITLE
ImportError: No module named pjsua

### ISSUE THREAD

**Issue by richilp** [irontec/bbs#4]
Hello there,

thanks for sharing bbs with the community.

We're getting this error trying to implement bbs in our Centos 7 server with Asterisk 16:

`Traceback (most recent call last):
  File "/usr/bin/bbs", line 9, in <module>
    load_entry_point('bbs==0.0.1', 'console_scripts', 'bbs')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "build/bdist.linux-x86_64/egg/bbs/main.py", line 43, in <module>
  File "build/bdist.linux-x86_64/egg/bbs/pjlib.py", line 19, in <module>
ImportError: No module named pjsua
`

Are we doing smth wrong?

Thanks for your help
Richi

**Comment by Kaian** [comment]
Hi Richi!

bbs requires pjsua python bindings in order to work as stated in the requeriments section of the README 

Most distributions doesn't include these bindings in a package, so you must compile them from pjproject (see https://trac.pjsip.org/repos/wiki/Python_SIP/Build_Install). 

Regards!

**Comment by richilp** [comment]
Hi Kaian,

yes, that was the problem. It's solved now.

Eskerrik asko !!
